### PR TITLE
Add Release CI

### PR DESCRIPTION
**Pull request by idea404**
- Adds CI yml for auto-releasing every new version
- Requires raising GH Actions rights in settings before this is merged

### CODE REVIEW

**Review by hedgar2017 — APPROVED** [review]
I don't know if it works, but approving just in case.

**Comment by idea404** [comment]
worked here: https://github.com/idea404/zksolc-bin-test/actions/runs/6096088068/job/16540925427
Assumes new versions in all directories are all published at the same time / on the same commit to master/main branch

**Comment by hedgar2017** [comment]
@idea404 please request a review from the devops team - they are managing our GitHub Actions.

**Comment by andrey-cybersec** [comment]
Looks good to me

**Review by andrey-cybersec — APPROVED** [review]

**Pull request merged**
